version: '3.7'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - node-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: 'b4chH04Ng0cD13p'
      ACCEPT_EULA: 'Y'
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
