name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Build & Push Docker Image to Docker Hub, then deploy to production cloud'
        required: true
        default: 'Manual build from GitHub UI'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [ self-hosted, builder ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tankietcute/node-app-prod:latest

  deploy:
    needs: build
    runs-on: [ self-hosted, prod ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull latest images
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml pull
      - name: Build and run
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
